const express = require("express");
const nodemailer = require("nodemailer");

const router = express.Router();

const transporter = nodemailer.createTransport({
  host: "smtp.zoho.com",
  port: 465,
      secure: true,
        auth: {
            user: process.env.ZOHO_EMAIL,
                pass: process.env.ZOHO_PASSWORD,
                  },
                  });

                  router.post("/", async (req, res) => {
                    try {
                        const {
                              name,
                                    company,
                                          email,
                                                phone,
                                                      category,
                                                            requirement,
                                                                } = req.body;

                                                                    // Basic validation
                                                                        if (!name || !email || !requirement) {
                                                                              return res.status(400).json({
                                                                                      success: false,
                                                                                              message: "Name, email and requirement are required.",
                                                                                                    });
                                                                                                        }

                                                                                                            // Email to your company
                                                                                                                await transporter.sendMail({
                                                                                                                      from: `"ANS ART CREATIONS Website" <${process.env.ZOHO_EMAIL}>`,
                                                                                                                            to: process.env.SALES_EMAIL,
                                                                                                                                  replyTo: email,
                                                                                                                                        subject: `New Quote Request${company ? ` - ${company}` : ""}`,
                                                                                                                                              html: `
                                                                                                                                                      <div style="font-family: Arial, sans-serif; line-height: 1.6;">
                                                                                                                                                                <h2>New Quote Request Received</h2>

                                                                                                                                                                          <hr>

                                                                                                                                                                                    <h3>Customer Details</h3>

                                                                                                                                                                                    <p>----------------------------</p>

                                                                                                                                                                                              <p><strong>Name:</strong> ${name}</p>
                                                                                                                                                                                                        <p><strong>Company:</strong> ${company || "Not provided"}</p>
                                                                                                                                                                                                                  <p><strong>Email:</strong> ${email}</p>
                                                                                                                                                                                                                            <p><strong>Phone:</strong> ${phone || "Not provided"}</p>
                                                                                                                                                                                                                            <h3>Enquiry Details</h3>

                                                                                                                                                                                                                                <p>----------------------------</p>

                                                                                                                                                                                                                                    <p><strong>Category:</strong> ${category || "Not provided"}</p>

                                                                                                                                                                                                                                        <p><strong>Requirement:</strong></p>
                                                                                                                                                                                                                                            <p>${requirement}</p>

                                                                                                                                                                                                                                                <p>----------------------------</p>

                                                                                                                                                                                                                                                    <p>
                                                                                                                                                                                                                                                          <strong>Submitted On:</strong><br>
                                                                                                                                                                                                                                                                ${new Date().toLocaleString("en-IN", {
                                                                                                                                                                                                                                                                        dateStyle: "medium",
                                                                                                                                                                                                                                                                                timeStyle: "short"
                                                                                                                                                                                                                                                                                      })}
                                                                                                                                                                                                                                                                                          </p>

                                                                                                                                                                                                                                                                              <p>
                                                                                                                                                                                                                                                                                          This enquiry was submitted through the ANS ART CREATIONS website.
                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                  `,
                                                                                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                                                                                          // Confirmation email to customer
                                                                                                                                                                                                                                                                                                                              await transporter.sendMail({
                                                                                                                                                                                                                                                                                                                                    from: `"ANS ART CREATIONS" <${process.env.ZOHO_EMAIL}>`,
                                                                                                                                                                                                                                                                                                                                          to: email,
                                                                                                                                                                                                                                                                                                                                                subject: "We Received Your Quote Request",
                                                                                                                                                                                                                                                                                                                                                      html: `
                                                                                                                                                                                                                                                                                                                                                              <div style="font-family: Arial, sans-serif; line-height: 1.6;">
                                                                                                                                                                                                                                                                                                                                                                        <h2>Thank You for Your Enquiry</h2>

                                                                                                                                                                                                                                                                                                                                                                                  <p>Dear ${name},</p>

                                                                                                                                                                                                                                                                                                                                                                                            <p>
                                                                                                                                                                                                                                                                                                                                                                                                        Thank you for contacting <strong>ANS ART CREATIONS</strong>.
                                                                                                                                                                                                                                                                                                                                                                                                                  </p>

                                                                                                                                                                                                                                                                                                                                                                                                                            <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                        We have successfully received your quotation request.
                                                                                                                                                                                                                                                                                                                                                                                                                                                    Our team will review your requirements and contact you shortly.
                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h3>Your Request</h3>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p><strong>Category:</strong> ${category || "Not provided"}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p><strong>Requirement:</strong> ${requirement}</p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  If you have any additional information or requirements,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              you can simply reply to this email.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Regards,<br>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <strong>ANS ART CREATIONS Team</strong>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  `,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          res.status(200).json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                success: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      message: "Quote request submitted successfully.",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.error("Quote email error:", error);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    res.status(500).json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          success: false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                message: "Unable to send quote request.",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      module.exports = router;